### ISSUE TITLE
Working with Pico 2.0?

### ISSUE THREAD

**Issue by cstanke** [PhrozenByte/pico-file-prefixes#2]
Hi,

New to PicoCMS and was hoping to use this file prefixes plugin. Is it working with the 2.0 release? I see the README has the older (non-YAML) configs and I don't seem to be getting the plugin to work in my handful of trials here.

Any guidance would be appreciated!

TIA,
-Chad

**Comment by PhrozenByte** [comment]
Yes, PicoFilePrefixes works just fine with Pico 2.0. However, it might not be so obvious how to proberly configure the plugin with Pico's YAML-based config. I'll update the `README.md` to reflect the new YAML-based config. Try a config like this:

```yaml
PicoFilePrefixes:
    recursiveDirs:
        - .
```

**Comment by cstanke** [comment]
Yep! Works great. I'm a little slow on the uptake. I should have figured this out myself. Sorry for using GitHub issue tracker for tech support.

Many regards!
